#!/usr/bin/env bash

VSCODE_EXTENSION_DIR="/home/$USER/.local/share/code-server/extensions"
MARKETPLACE_URL="https://marketplace.visualstudio.com/_apis/public/gallery"

for extension in "$@"
do
    publisher=${extension%.*}
    name=${extension#*.}
    dir="$VSCODE_EXTENSION_DIR/${publisher}_${name}"
    url="$MARKETPLACE_URL/publishers/$publisher/vsextensions/$name/latest/vspackage"
	echo "...Installing $extension ($url) to $dir"
    mkdir -p $dir && (curl -JLs --retry 5 $url | bsdtar --strip-components=1 -xf - -C $dir extension)
done

